spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://order-postgres:5432/order_db
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:kafka:9092}
    consumer:
      group-id: ${app.kafka.consumer-group}
      auto-offset-reset: earliest
    producer:
      retries: 3

server:
  port: 8083

external:
  user-service:
    url: http://user-service:8081

app:
  kafka:
    orders-topic: orders
    payments-topic: payments
    consumer-group: order-service-payments

logging:
  level:
    root: INFO
    com.internship.orderservice: INFO
    org.springframework.kafka: INFO
    org.apache.kafka: WARN
    org.hibernate: WARN